import crypto from 'node:crypto';
const taskFrom=data=>data?.Task||data?.task||data||{};
const expensesFrom=data=>Array.isArray(data)?data:data?.Expenses||data?.expenses||[];
const text=value=>String(value??'').trim();
const tag=(error,phase)=>{if(error&&typeof error==='object'&&!Object.hasOwn(error,'mutationPhase'))Object.defineProperty(error,'mutationPhase',{value:phase,enumerable:false});return error};
const definitiveNoMutation=error=>[400,401,403,404,405,422].includes(Number(error?.status));
const firstId=value=>String(value??'').split(/\|\||\s*,\s*/).map(text).find(x=>/^\d+$/u.test(x))||'';
export const apiFieldKey=value=>{const id=String(value||'').match(/(\d+)$/u)?.[1];if(!id)throw Error('API_CUSTOM_FIELD_ID_INVALID');return `Field${id}`};
export const closeOperationKey=({scope='single',scopeId='',taskId,solution,minutes})=>`${scope}:${scopeId||taskId}:${taskId}:${crypto.createHash('sha256').update(`${taskId}\0${solution}\0${minutes}`).digest('hex').slice(0,20)}`;
const marker=key=>`TG_CLOSE_${crypto.createHash('sha256').update(String(key)).digest('hex').slice(0,20)}`;
function assertCloseRights(root,solutionKey,statusId){const rights=root?.Rights||{},fieldId=solutionKey.slice(5),field=(root?.TaskType?.TaskTypeFields||[]).find(x=>String(x.Id)===fieldId),editable=n=>(Number(n)||0)&4,to=new Set((rights.ToStatuses||[]).map(x=>String(x?.Id??x)));if(!editable(field?.Rights))throw Error('API_SOLUTION_EDIT_FORBIDDEN');if(!editable(rights.Status)||!to.has(String(statusId)))throw Error('API_STATUS_TRANSITION_FORBIDDEN')}
export class ApiCloseCoordinator{
 constructor({config,store,reader,writer}={}){this.config=config;this.store=store;this.reader=reader;this.writer=writer}
 async task(id){return this.reader.getTask(id)}
 async expenses(id){return expensesFrom((await this.reader.getTaskExpenses(id)).data)}
 async run({operationKey,taskId,solution,minutes}){const id=String(taskId||''),mins=Number(minutes),wanted=text(solution),expenseMarker=marker(operationKey),solutionKey=apiFieldKey(this.config.fields.solution),closed=String(this.config.statuses.closed);if(!/^\d+$/u.test(id)||!wanted||!Number.isInteger(mins)||mins<1||mins>1440)throw tag(Error('API_CLOSE_INPUT_INVALID'),'preflight');let op=this.store.getApiClose(operationKey);if(!op){this.store.createApiClose({operationKey,taskId:id,state:'prepared',solution:wanted,minutes:mins,expenseMarker});op=this.store.getApiClose(operationKey)}if(op.state==='legacy_attempted')throw tag(Error('API_CLOSE_LEGACY_RESULT_REQUIRES_REVIEW'),'verify');if(op.state==='completed'&&op.last_error==='LEGACY_FALLBACK')return{state:'closed',legacy:true};let response,root,task,rows,matches,taskMatches;try{response=await this.task(id);root=response.data||{};task=taskFrom(root);rows=await this.expenses(id);matches=rows.filter(x=>text(x.Comments||x.Comment)===expenseMarker);taskMatches=String(task.StatusId)===closed&&text(task[solutionKey])===wanted}catch(error){throw tag(error,op.state==='prepared'?'read':'verify')}if(matches.length>1||matches.some(x=>Number(x.Minutes)!==mins))throw tag(Error('API_CLOSE_EXPENSE_MARKER_MISMATCH'),'verify');if(taskMatches&&matches.length===1){this.store.updateApiClose(operationKey,{state:'completed',completed_at:new Date().toISOString(),last_error:''});return{state:'closed',recovered:true}}if(op.state==='uncertain'&&!(op.last_error==='TASK_MUTATION_UNCERTAIN'&&taskMatches&&!matches.length))throw tag(Error('API_CLOSE_UNCERTAIN_REQUIRES_REVIEW'),'verify');if(!taskMatches){if(String(task.StatusId)===closed)throw tag(Error('API_CLOSE_ALREADY_CLOSED_DIFFERENT_RESULT'),'stale');try{assertCloseRights(root,solutionKey,closed)}catch(error){throw tag(error,'preflight')}const changed=text(task.Changed);this.store.updateApiClose(operationKey,{state:'task_attempted',before_changed:changed,updated_at:new Date().toISOString()});try{await this.writer.updateTask(id,{StatusId:closed,[solutionKey]:wanted,Changed:changed})}catch(error){if(definitiveNoMutation(error)&&Number(error.status)!==409){this.store.updateApiClose(operationKey,{state:'prepared',last_error:String(error.code||error.message)});throw tag(error,'write')}try{task=taskFrom((await this.task(id)).data);taskMatches=String(task.StatusId)===closed&&text(task[solutionKey])===wanted}catch{}if(!taskMatches){this.store.updateApiClose(operationKey,{state:'uncertain',last_error:'TASK_MUTATION_UNCERTAIN'});throw tag(Error('API_CLOSE_TASK_UNCERTAIN'),'verify')}}this.store.updateApiClose(operationKey,{state:'task_verified',task_verified_at:new Date().toISOString(),last_error:''})}
  try{rows=await this.expenses(id)}catch(error){throw tag(error,'verify')}matches=rows.filter(x=>text(x.Comments||x.Comment)===expenseMarker);if(!matches.length){const userId=firstId(task.ExecutorIds)||String(root?.Rights?.CurrentUserId||'');this.store.updateApiClose(operationKey,{state:'expense_attempted',expense_user_id:userId,updated_at:new Date().toISOString()});try{await this.writer.addTaskExpense({TaskId:id,Minutes:mins,...(userId?{UserId:userId}:{}),Comments:expenseMarker})}catch(error){try{matches=(await this.expenses(id)).filter(x=>text(x.Comments||x.Comment)===expenseMarker)}catch{}if(matches.length!==1){this.store.updateApiClose(operationKey,{state:definitiveNoMutation(error)?'task_verified':'uncertain',last_error:definitiveNoMutation(error)?String(error.code||error.message):'EXPENSE_MUTATION_UNCERTAIN'});throw tag(error,'verify')}}}
  rows=await this.expenses(id);matches=rows.filter(x=>text(x.Comments||x.Comment)===expenseMarker);if(matches.length!==1||Number(matches[0].Minutes)!==mins){this.store.updateApiClose(operationKey,{state:'uncertain',last_error:'EXPENSE_VERIFY_FAILED'});throw tag(Error('API_CLOSE_EXPENSE_VERIFY_FAILED'),'verify')}task=taskFrom((await this.task(id)).data);if(String(task.StatusId)!==closed||text(task[solutionKey])!==wanted)throw tag(Error('API_CLOSE_FINAL_VERIFY_FAILED'),'verify');this.store.updateApiClose(operationKey,{state:'completed',expense_verified_at:new Date().toISOString(),completed_at:new Date().toISOString(),last_error:''});return{state:'closed'} }
}
