const MUTATION_CAPABILITY=Symbol('INTRASERVICE_API_MUTATION');
const finiteInt=(value,{min,max,name})=>{const n=Number(value);if(!Number.isInteger(n)||n<min||n>max)throw Error(`API_${name}_INVALID`);return n};
const plainObject=(value,name)=>{if(!value||typeof value!=='object'||Array.isArray(value))throw Error(`API_${name}_INVALID`);return Object.fromEntries(Object.entries(value).filter(([,item])=>item!==undefined))};

export class IntraServiceApiHttpError extends Error{
 constructor(status,responseBody=''){super(`API_HTTP_${status}`);this.name='IntraServiceApiHttpError';this.status=Number(status);this.code=status===409?'API_CONFLICT':`API_HTTP_${status}`;Object.defineProperty(this,'responseBody',{value:String(responseBody||''),enumerable:false})}
}
export class IntraServiceApiClient{
 constructor({baseUrl,credentials,timeoutMs=15000,fetchImpl=fetch}={}){this.baseUrl=String(baseUrl||'').replace(/\/$/u,'');this.origin=new URL(this.baseUrl).origin;this.credentials=credentials||{};this.timeoutMs=finiteInt(timeoutMs,{min:100,max:120000,name:'TIMEOUT'});this.fetchImpl=fetchImpl}
 authHeader(){const login=this.credentials.login||'',password=this.credentials.password||'';if(!login||!password)throw Error('API_CREDENTIALS_MISSING');return `Basic ${Buffer.from(`${login}:${password}`,'utf8').toString('base64')}`}
 url(resource,query={}){const url=new URL(`/api/${String(resource||'').replace(/^\/+/, '')}`,this.baseUrl);if(url.origin!==this.origin)throw Error('API_CROSS_ORIGIN_BLOCKED');for(const [key,value] of Object.entries(query))if(value!==undefined&&value!==null&&value!=='')url.searchParams.set(key,Array.isArray(value)?value.join(','):String(value));return url}
 async request(resource,{query={},method='GET',body,capability}={}){const verb=String(method).toUpperCase();if(verb!=='GET'&&capability!==MUTATION_CAPABILITY)throw Error('API_READ_ONLY_CLIENT');if(!['GET','POST','PUT'].includes(verb))throw Error('API_METHOD_BLOCKED');const hasBody=verb!=='GET'&&body!==undefined,response=await this.fetchImpl(this.url(resource,query),{method:verb,redirect:'manual',signal:AbortSignal.timeout(this.timeoutMs),headers:{Accept:'application/json',Authorization:this.authHeader(),'Device-Name':'IntraService Telegram Bot Community','Device-Version':'0.2-beta',...(hasBody?{'Content-Type':'application/json; charset=utf-8'}:{})},...(hasBody?{body:JSON.stringify(body)}:{})});if(response.status>=300&&response.status<400)throw Error(`API_REDIRECT_BLOCKED_${response.status}`);const text=await response.text();if(!response.ok)throw new IntraServiceApiHttpError(response.status,text);if(!text)return{data:null,status:response.status};if(!/json/iu.test(response.headers.get('content-type')||'')&&!/^\s*[\[{]/u.test(text))throw Error('API_RESPONSE_NOT_JSON');try{return{data:JSON.parse(text),status:response.status,apiVersion:response.headers.get('x-api-version')||''}}catch{throw Error('API_JSON_INVALID')}}
 listTasks({page=1,pageSize=500}={}){return this.request('task',{query:{fields:['Id','Name','Description','StatusId','StatusName','ExecutorIds','ExecutorNames','CategoryIds','CategoryNames','Changed'],page,pagesize:pageSize}})}
 getTask(id,{include=['STATUS','TASKTYPE','USERTASKRIGHTS']}={}){if(!/^\d+$/u.test(String(id)))throw Error('API_TASK_ID_INVALID');return this.request(`task/${id}`,{query:{include}})}
 getNewTask({serviceId,taskTypeId}={}){if(!/^\d+$/u.test(String(serviceId)))throw Error('API_SERVICE_ID_INVALID');if(!/^\d+$/u.test(String(taskTypeId)))throw Error('API_TASK_TYPE_ID_INVALID');return this.request('newtask',{query:{serviceid:serviceId,tasktypeid:taskTypeId,include:['USERTASKRIGHTS','TASKTYPE','TASKTYPESETTINGS','STATUS']}})}
 getTaskExpenses(taskId){if(!/^\d+$/u.test(String(taskId)))throw Error('API_TASK_ID_INVALID');return this.request('taskexpenses',{query:{taskid:taskId,fields:['Id','TaskId','Minutes','UserId','Comment','Comments','Date'],page:1,pagesize:2000}})}
}
export class IntraServiceApiMutationClient extends IntraServiceApiClient{
 mutate(resource,method,body){return this.request(resource,{method,body,capability:MUTATION_CAPABILITY})}
 updateTask(id,patch){if(!/^\d+$/u.test(String(id)))throw Error('API_TASK_ID_INVALID');const body=plainObject(patch,'TASK_PATCH');if(!String(body.Changed||'').trim())throw Error('API_CHANGED_REQUIRED');return this.mutate(`task/${id}`,'PUT',body)}
 createTask(task){const body=plainObject(task,'TASK_CREATE');for(const field of ['ServiceId','TypeId','Name'])if(!String(body[field]||'').trim())throw Error(`API_CREATE_${field.toUpperCase()}_REQUIRED`);return this.mutate('task','POST',body)}
 addTaskExpense(expense){const body=plainObject(expense,'EXPENSE');if(!/^\d+$/u.test(String(body.TaskId||'')))throw Error('API_TASK_ID_INVALID');body.Minutes=finiteInt(body.Minutes,{min:1,max:1440,name:'EXPENSE_MINUTES'});const allowed=new Set(['TaskId','Minutes','UserId','Comments','Date']);for(const key of Object.keys(body))if(!allowed.has(key))throw Error(`API_EXPENSE_FIELD_BLOCKED_${key.toUpperCase()}`);return this.mutate('taskexpenses','POST',body)}
}
