import {randomUUID} from 'node:crypto';
import {IntraServiceClient as PlaywrightClient} from './intraservice_client.mjs';
import {IntraServiceApiClient,IntraServiceApiMutationClient} from './intraservice_api_client.mjs';
import {ApiCloseCoordinator,apiFieldKey,closeOperationKey} from './api_close.mjs';
const taskFrom=data=>data?.Task||data?.task||data||{};
const tasksFrom=data=>Array.isArray(data)?data:data?.Tasks||data?.tasks||[];
const expensesFrom=data=>Array.isArray(data)?data:data?.Expenses||data?.expenses||[];
const ids=value=>String(value??'').split(/\|\||\s*,\s*/).map(x=>x.trim()).filter(Boolean);
const names=value=>String(value??'').split(/\|\||\s*,\s*/).map(x=>x.trim()).filter(Boolean);
const pairs=(idValue,nameValue)=>{const a=ids(idValue),b=names(nameValue);return a.map((id,i)=>({id,name:b[i]||id}))};
const phase=(error,name)=>{if(error&&typeof error==='object'&&!Object.hasOwn(error,'mutationPhase'))Object.defineProperty(error,'mutationPhase',{value:name,enumerable:false});return error};
const safeFallback=error=>['read','preflight'].includes(error?.mutationPhase)||(error?.mutationPhase==='write'&&[400,401,403,404,405,422].includes(Number(error?.status)));
export class HybridIntraServiceClient{
 constructor({config,credentials,root,store,fetchImpl=fetch}={}){this.config=config;this.store=store;this.legacy=new PlaywrightClient({config,credentials,root});this.enabled=config.api?.enabled===true;this.flags=config.api?.mutations||{};if(this.enabled){this.reader=new IntraServiceApiClient({baseUrl:config.base_url,credentials,timeoutMs:config.api.timeout_ms||15000,fetchImpl});this.writer=new IntraServiceApiMutationClient({baseUrl:config.base_url,credentials,timeoutMs:config.api.timeout_ms||15000,fetchImpl});this.closeCoordinator=new ApiCloseCoordinator({config,store,reader:this.reader,writer:this.writer})}}
 audit(operation,result,details={}){this.store?.audit({action:'api_transport',result,details:{operation,...details}})}
 async close(){await this.legacy.close()}
 async listTasks(options={}){if(!this.enabled)return this.legacy.listTasks(options);try{const response=await this.reader.listTasks({pageSize:Math.min(2000,Number(options.maxPages||this.config.task_list_pages||20)*25)}),rows=tasksFrom(response.data);const tasks=rows.map(x=>({id:String(x.Id),status:String(x.StatusName||x.Status||x.StatusId||''),title:String(x.Name||x.Title||'Untitled'),executor:String(x.ExecutorNames||''),changed:String(x.Changed||'')})).filter(x=>/^\d+$/u.test(x.id));this.audit('list','ok',{count:tasks.length});return tasks}catch(error){this.audit('list','fallback',{code:String(error.code||error.message)});return this.legacy.listTasks(options)}}
 async apiTask(id){const response=await this.reader.getTask(id),task=taskFrom(response.data),expenseResponse=await this.reader.getTaskExpenses(id),expenseRows=expensesFrom(expenseResponse.data),field=this.config.fields;return{id:String(task.Id||id),title:String(task.Name||''),description:String(task.Description||''),requester:String(task[apiFieldKey(field.requester)]||''),locationId:String(task[apiFieldKey(field.location)]||''),location:String(task.LocationName||task[apiFieldKey(field.location)]||''),cabinet:String(task[apiFieldKey(field.cabinet)]||''),solution:String(task[apiFieldKey(field.solution)]||''),statusId:String(task.StatusId||''),status:String(task.StatusName||task.Status?.Name||task.StatusId||''),executors:pairs(task.ExecutorIds,task.ExecutorNames),categories:pairs(task.CategoryIds,task.CategoryNames),expenseTotals:[expenseRows.reduce((sum,x)=>sum+Number(x.Minutes||0),0)],changed:String(task.Changed||''),raw:response.data}}
 async getTask(id){if(!this.enabled)return this.legacy.getTask(id);try{const task=await this.apiTask(id);this.audit('card','ok');return task}catch(error){this.audit('card','fallback',{code:String(error.code||error.message)});return this.legacy.getTask(id)}}
 async apiCreate(draft){let defaults;try{defaults=await this.reader.getNewTask({serviceId:this.config.api.service_id,taskTypeId:this.config.api.task_type_id})}catch(error){throw phase(error,'read')}const root=defaults.data||{},task=taskFrom(root),rights=root.Rights||{},body={ServiceId:Number(this.config.api.service_id),TypeId:Number(this.config.api.task_type_id),Name:String(draft.title),Description:String(draft.description||draft.title),StatusId:Number(this.config.statuses.open||task.StatusId),CreatorId:Number(task.CreatorId||rights.CurrentUserId),PriorityId:Number(task.PriorityId),WorkflowId:Number(task.WorkflowId),ReactionDate:task.ReactionDate,Deadline:task.Deadline,ExecutorIds:(draft.executorIds?.length?draft.executorIds:[rights.CurrentUserId||task.CreatorId]).filter(Boolean).join(','),CategoryIds:(draft.categoryIds||[]).join(','),[apiFieldKey(this.config.fields.requester)]:String(draft.requester||''),[apiFieldKey(this.config.fields.location)]:String(draft.locationId||''),[apiFieldKey(this.config.fields.cabinet)]:String(draft.cabinet||'')};let created;try{created=await this.writer.createTask(body)}catch(error){throw phase(error,'write')}const id=String(taskFrom(created.data).Id||'');if(!/^\d+$/u.test(id))throw phase(Error('API_CREATE_ID_MISSING'),'verify');let saved;try{saved=await this.apiTask(id)}catch(error){throw phase(error,'verify')}if(saved.title!==body.Name||saved.statusId!==String(body.StatusId)||saved.cabinet!==String(draft.cabinet)||saved.locationId!==String(draft.locationId))throw phase(Error('API_CREATE_VERIFY_FAILED'),'verify');return saved}
 async createTask(draft){if(!this.enabled||this.flags.create!==true)return this.legacy.createTask(draft);try{const saved=await this.apiCreate(draft);this.audit('create','ok');return saved}catch(error){if(!safeFallback(error)){this.audit('create','blocked',{phase:error.mutationPhase||'',code:String(error.code||error.message)});throw error}this.audit('create','fallback',{phase:error.mutationPhase||'',code:String(error.code||error.message)});return this.legacy.createTask(draft)}}
 async closeTask(id,{solution,minutes,operationId='',scope='single'}={}){if(!this.enabled||this.flags.close!==true||(scope==='batch'&&this.flags.batch_close!==true))return this.legacy.closeTask(id,{solution,minutes});const operationKey=closeOperationKey({scope,scopeId:operationId||randomUUID(),taskId:id,solution,minutes});try{const result=await this.closeCoordinator.run({operationKey,taskId:id,solution,minutes});this.audit(scope==='batch'?'batch_close':'close','ok');return result}catch(error){if(!safeFallback(error)){this.audit('close','blocked',{phase:error.mutationPhase||'',code:String(error.code||error.message)});throw error}this.store.updateApiClose(operationKey,{state:'legacy_attempted',updated_at:new Date().toISOString(),last_error:'LEGACY_FALLBACK_STARTED'});try{const result=await this.legacy.closeTask(id,{solution,minutes});this.store.updateApiClose(operationKey,{state:'completed',completed_at:new Date().toISOString(),last_error:'LEGACY_FALLBACK'});this.audit('close','fallback');return result}catch(legacyError){this.store.updateApiClose(operationKey,{state:'legacy_attempted',last_error:'LEGACY_FALLBACK_UNCERTAIN'});throw legacyError}}}
}
