import http from 'http';
import https from 'https';
import tls from 'tls';

function responseJson(res,method,resolve,reject){let body='';res.setEncoding('utf8');res.on('error',reject);res.on('data',chunk=>{body+=chunk;if(body.length>10_000_000)res.destroy(Error('TELEGRAM_RESPONSE_TOO_LARGE'))});res.on('end',()=>{let data;try{data=JSON.parse(body)}catch{return reject(Error(`Telegram ${method}: bad JSON status=${res.statusCode}`))}if(!data.ok)return reject(Error(`Telegram ${method}: ${String(data.description||`HTTP ${res.statusCode}`).slice(0,300)}`));resolve(data.result)})}

function proxyAuthorization(proxy){if(!proxy.username&&!proxy.password)return null;return `Basic ${Buffer.from(`${decodeURIComponent(proxy.username)}:${decodeURIComponent(proxy.password)}`).toString('base64')}`}

export class TelegramClient{
 constructor({token,proxy='',baseUrl='https://api.telegram.org',rejectUnauthorized=true}={}){if(!token)throw Error('TELEGRAM_TOKEN_MISSING');this.token=String(token);this.proxy=String(proxy||'');this.baseUrl=String(baseUrl).replace(/\/$/u,'');this.rejectUnauthorized=rejectUnauthorized}
 call(method,payload={},timeoutMs=40000){if(!/^[A-Za-z][A-Za-z0-9_]*$/u.test(String(method)))return Promise.reject(Error('TELEGRAM_METHOD_INVALID'));const target=new URL(`${this.baseUrl}/bot${this.token}/${method}`),body=JSON.stringify(payload??{}),headers={'content-type':'application/json','content-length':Buffer.byteLength(body)};return this.proxy?this.#proxyPost(target,body,headers,method,timeoutMs):this.#directPost(target,body,headers,method,timeoutMs)}
 #directPost(target,body,headers,method,timeoutMs){return new Promise((resolve,reject)=>{const transport=target.protocol==='https:'?https:http,req=transport.request(target,{method:'POST',headers,rejectUnauthorized:this.rejectUnauthorized},res=>responseJson(res,method,resolve,reject));req.setTimeout(timeoutMs,()=>req.destroy(Error(`Telegram ${method}: timeout`)));req.on('error',reject);req.end(body)})}
 #proxyPost(target,body,headers,method,timeoutMs){return new Promise((resolve,reject)=>{if(target.protocol!=='https:')return reject(Error('TELEGRAM_PROXY_REQUIRES_HTTPS_TARGET'));let proxy;try{proxy=new URL(this.proxy)}catch{return reject(Error('TELEGRAM_PROXY_INVALID'))}if(!['http:','https:'].includes(proxy.protocol))return reject(Error(`TELEGRAM_PROXY_UNSUPPORTED:${proxy.protocol}`));const transport=proxy.protocol==='https:'?https:http,port=Number(target.port||443),connectHeaders={host:`${target.hostname}:${port}`},auth=proxyAuthorization(proxy);if(auth)connectHeaders['proxy-authorization']=auth;let settled=false;const fail=e=>{if(settled)return;settled=true;reject(e instanceof Error?e:Error(String(e)))};const connectReq=transport.request({hostname:proxy.hostname,port:Number(proxy.port||(/https/u.test(proxy.protocol)?443:80)),method:'CONNECT',path:`${target.hostname}:${port}`,headers:connectHeaders,rejectUnauthorized:this.rejectUnauthorized});connectReq.setTimeout(timeoutMs,()=>connectReq.destroy(Error(`Telegram ${method}: proxy timeout`)));connectReq.on('error',fail);connectReq.on('connect',(res,socket,head)=>{if(res.statusCode!==200){socket.destroy();return fail(Error(`Telegram ${method}: proxy CONNECT ${res.statusCode}`))}if(head?.length)socket.unshift(head);const secure=tls.connect({socket,servername:target.hostname,rejectUnauthorized:this.rejectUnauthorized});secure.setTimeout(timeoutMs,()=>secure.destroy(Error(`Telegram ${method}: timeout`)));secure.once('error',fail);secure.once('secureConnect',()=>{const agent=new https.Agent({keepAlive:false});agent.createConnection=(_options,callback)=>{callback?.(null,secure);return secure};const req=https.request({hostname:target.hostname,port,path:target.pathname+target.search,method:'POST',headers,agent,rejectUnauthorized:this.rejectUnauthorized},response=>{response.once('end',()=>agent.destroy());responseJson(response,method,value=>{if(settled)return;settled=true;resolve(value)},fail)});req.setTimeout(timeoutMs,()=>req.destroy(Error(`Telegram ${method}: timeout`)));req.on('error',fail);req.end(body)})});connectReq.end()})}
}
