import {createHash} from 'node:crypto';

export const PAGE_SIZE=6;
export const TEMPLATE_PICKER_PAGE_SIZE=8;
export const TEMPLATE_CATALOG_PAGE_SIZE=10;

const short=(v,n=50)=>{const s=String(v||'Untitled').replace(/\s+/g,' ').trim();return s.length<=n?s:s.slice(0,n-1)+'…'};
const safePage=(page,total,size)=>Math.max(0,Math.min(Number(page)||0,Math.max(1,Math.ceil((Number(total)||0)/size))-1));
export const templateCategoryKey=category=>createHash('sha256').update(String(category||'').trim()).digest('hex').slice(0,12);

export function mainKeyboard(){return{keyboard:[[{text:'📋 Tickets'},{text:'➕ Create'}],[{text:'💬 Templates'},{text:'❓ Help'}]],resize_keyboard:true,is_persistent:true}}
export function ticketsKeyboard(){return{inline_keyboard:[[{text:'📋 Open tickets',callback_data:'list:0'}],[{text:'↩️ Main menu',callback_data:'main'}]]}}
export function ticketListView(tasks,{page=0,selected=[],selectionMode=false}={}){const pages=Math.max(1,Math.ceil(tasks.length/PAGE_SIZE)),safe=Math.max(0,Math.min(Number(page)||0,pages-1)),rows=tasks.slice(safe*PAGE_SIZE,safe*PAGE_SIZE+PAGE_SIZE),chosen=new Set(selected.map(String)),kb=[];for(const task of rows){const id=String(task.id),action=selectionMode?'sel':'view',mark=selectionMode?(chosen.has(id)?'☑ ':'☐ '):'';kb.push([{text:`${mark}#${id} — ${short(task.title,54)}`,callback_data:`${action}:${safe}:${id}`}])}const nav=[];if(safe>0)nav.push({text:'◀️',callback_data:`list:${safe-1}`});nav.push({text:`${safe+1}/${pages}`,callback_data:`list:${safe}`});if(safe<pages-1)nav.push({text:'▶️',callback_data:`list:${safe+1}`});kb.push(nav);if(selectionMode&&chosen.size)kb.push([{text:`✅ Close selected (${chosen.size})`,callback_data:`batch:${safe}`}]);kb.push([{text:selectionMode?'↩️ Normal mode':`☑ Selection mode${chosen.size?` (${chosen.size})`:''}`,callback_data:`mode:${safe}:${selectionMode?'0':'1'}`}]);kb.push([{text:'🔄 Refresh',callback_data:`refresh:${safe}`},{text:'↩️ Tickets',callback_data:'tickets'}]);const hint=selectionMode?'Selection mode: tap full-width tickets to toggle them.':'Tap a full-width ticket to open its card.';return{text:`📋 Open tickets\n\nFound: ${tasks.length}. Page ${safe+1}/${pages}.\n\n${hint}`,reply_markup:{inline_keyboard:kb},page:safe,pages}}
export function ticketCardText(t){return`#${t.id} [${t.status||'—'}]\n${t.title||'Untitled'}\n\nDescription: ${t.description||'—'}\nLocation: ${t.location||'—'}\nCabinet: ${t.cabinet||'—'}\nExecutor: ${(t.executors||[]).map(x=>x.name).join(', ')||'unassigned'}\nCategory: ${(t.categories||[]).map(x=>x.name).join(', ')||'—'}\nSolution: ${t.solution||'—'}`}
export function ticketCardKeyboard(t,page=0){return{inline_keyboard:[[{text:'✅ Close',callback_data:`close:${page}:${t.id}`}],[{text:'↩️ Back to list',callback_data:`list:${page}`}]]}}

export function templateCategoriesKeyboard(rows,{purpose='pick',batch=false}={}){const pick=purpose==='pick',kb=(rows||[]).map(x=>[{text:`📁 ${short(x.category,45)} · ${Number(x.count)||0}`,callback_data:`${pick?'pcat':'mcat'}:${templateCategoryKey(x.category)}:0`}]);if(pick){kb.push([{text:'⭐ Popular',callback_data:'ppop'},{text:'📚 All',callback_data:'pall:0'}]);kb.push([{text:'⌨️ Enter manually',callback_data:batch?'bmanual':'manual'}]);kb.push([{text:'❌ Cancel',callback_data:'cancel'}])}else{kb.push([{text:'📚 All active',callback_data:'mall:0'},{text:'⏸ Disabled',callback_data:'mdis:0'}]);kb.push([{text:'➕ Add with /template',callback_data:'template_help'}]);kb.push([{text:'↩️ Main menu',callback_data:'main'}])}return{inline_keyboard:kb}}
export function templatePickerKeyboard(rows,{batch=false,page=0,total=rows.length,scope='popular',categoryKey=''}={}){const prefix=batch?'btpl':'tpl',safe=safePage(page,total,TEMPLATE_PICKER_PAGE_SIZE),pages=Math.max(1,Math.ceil((Number(total)||0)/TEMPLATE_PICKER_PAGE_SIZE)),kb=rows.map(x=>[{text:`💬 ${short(x.name,40)} · ${x.default_minutes} min`,callback_data:`${prefix}:${x.id}`}]);if(scope!=='popular'&&pages>1){const nav=[];if(safe>0)nav.push({text:'◀️',callback_data:scope==='category'?`pcat:${categoryKey}:${safe-1}`:`pall:${safe-1}`});nav.push({text:`${safe+1}/${pages}`,callback_data:'noop'});if(safe<pages-1)nav.push({text:'▶️',callback_data:scope==='category'?`pcat:${categoryKey}:${safe+1}`:`pall:${safe+1}`});kb.push(nav)}kb.push([{text:'🗂 Categories',callback_data:'pcats'},{text:'⭐ Popular',callback_data:'ppop'}]);kb.push([{text:'⌨️ Enter manually',callback_data:batch?'bmanual':'manual'}]);kb.push([{text:'❌ Cancel',callback_data:'cancel'}]);return{inline_keyboard:kb}}
export function templatesKeyboard(rows,{page=0,total=rows.length,scope='all',categoryKey=''}={}){const safe=safePage(page,total,TEMPLATE_CATALOG_PAGE_SIZE),pages=Math.max(1,Math.ceil((Number(total)||0)/TEMPLATE_CATALOG_PAGE_SIZE)),pageCallback=p=>scope==='category'?`mcat:${categoryKey}:${p}`:scope==='disabled'?`mdis:${p}`:`mall:${p}`,kb=rows.map(x=>[{text:`${x.active?'💬':'⏸'} ${short(x.name,42)} · ${x.default_minutes} min`,callback_data:`template:${x.id}`}]);if(pages>1){const nav=[];if(safe>0)nav.push({text:'◀️',callback_data:pageCallback(safe-1)});nav.push({text:`${safe+1}/${pages}`,callback_data:'noop'});if(safe<pages-1)nav.push({text:'▶️',callback_data:pageCallback(safe+1)});kb.push(nav)}kb.push([{text:'🗂 Categories',callback_data:'mcats'}]);kb.push([{text:'➕ Add with /template',callback_data:'template_help'}]);kb.push([{text:'↩️ Main menu',callback_data:'main'}]);return{inline_keyboard:kb}}
export function minuteKeyboard(){return{inline_keyboard:[[5,10,15].map(n=>({text:`${n} min`,callback_data:`min:${n}`})),[30,45,60].map(n=>({text:`${n} min`,callback_data:`min:${n}`})),[{text:'⌨️ Enter manually',callback_data:'min:manual'}],[{text:'❌ Cancel',callback_data:'cancel'}]]}}
export function confirmKeyboard(kind='single'){return{inline_keyboard:[[{text:'✅ Confirm',callback_data:`confirm:${kind}`}],[{text:'❌ Cancel',callback_data:'cancel'}]]}}
export function createConfirmKeyboard(){return{inline_keyboard:[[{text:'✅ Confirm creation',callback_data:'confirm:create'}],[{text:'❌ Cancel',callback_data:'cancel'}]]}}
